"""initial schema

Revision ID: 9e069838771d
Revises:
Create Date: 2026-02-12 22:44:03.322858

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9e069838771d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboards",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.Text(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.Text(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "saved_views",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("metrics_csv", sa.Text(), nullable=False),
        sa.Column("window_amount", sa.Integer(), nullable=False),
        sa.Column("window_unit", sa.Text(), nullable=False),
        sa.Column("step_amount", sa.Integer(), nullable=False),
        sa.Column("step_unit", sa.Text(), nullable=False),
        sa.Column("compare_enabled", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("label_filters_json", sa.Text(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("query_string", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.Text(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.Text(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dashboard_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dashboard_id", sa.Integer(), nullable=False),
        sa.Column("saved_view_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.Text(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["dashboard_id"], ["dashboards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["saved_view_id"], ["saved_views.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dashboard_id", "saved_view_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dashboard_items")
    op.drop_table("saved_views")
    op.drop_table("dashboards")
    # ### end Alembic commands ###
